<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>QuadStickConfigManager</AssemblyName>
    <Version>1.7.0</Version>
    <ApplicationIcon>Assets/AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Strings.qps-ploc.resx" Condition="'$(Configuration)' == 'Release'" />
    <EmbeddedResource Update="Strings.resx" Generator="MSBuild:Compile" StronglyTypedLanguage="CSharp" StronglyTypedNamespace="QuadStick.App" StronglyTypedClassName="Strings" PublicClass="true" StronglyTypedFileName="$(IntermediateOutputPath)Strings.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/AppIcon.png" />
    <AvaloniaResource Include="Assets/QuadStick.png" />
    <AvaloniaResource Include="Assets/QuadStickBack.png" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="QuadStick.App.Tests" />
    <InternalsVisibleTo Include="RenderPreview" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="PostHog" Version="2.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../QuadStick.Core/QuadStick.Core.csproj" />
    <ProjectReference Include="../QuadStick.Application/QuadStick.Application.csproj" />
    <ProjectReference Include="../QuadStick.Infrastructure/QuadStick.Infrastructure.csproj" />
  </ItemGroup>
</Project>
