<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuadStick.Core</RootNamespace>
    <Version>1.7.0</Version>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <NoWarn>$(NoWarn);CA1863</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates/Resources/default-template.csv" LogicalName="DefaultTemplate" />
    <EmbeddedResource Include="Validation/Resources/validation.json" LogicalName="ValidationJson" />
    <EmbeddedResource Include="Preferences/Resources/preferences.json" LogicalName="PreferencesJson" />
    <EmbeddedResource Include="Preferences/Resources/preferences.*.json" WithCulture="false"
                      LogicalName="PreferencesJson.$([System.String]::Copy('%(Filename)').Substring(12))"
                      Exclude="Preferences/Resources/preferences.qps-ploc.json" />
    <EmbeddedResource Include="Preferences/Resources/preferences.qps-ploc.json" LogicalName="PreferencesJson.qps-ploc"
                      WithCulture="false" Condition="'$(Configuration)' != 'Release'" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Strings.qps-ploc.resx" Condition="'$(Configuration)' == 'Release'" />
    <EmbeddedResource Update="Strings.resx" Generator="MSBuild:Compile"
                      StronglyTypedLanguage="CSharp" StronglyTypedNamespace="QuadStick.Format"
                      StronglyTypedClassName="Strings" PublicClass="true"
                      StronglyTypedFileName="$(IntermediateOutputPath)Strings.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QuadStick.Integration.Tests" />
  </ItemGroup>
</Project>
